# Generated by Django 5.2.11 on 2026-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('descripcion', models.TextField()),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
    ]
